version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
#         image: ivelin1936/m5_web
        ports:
            - 8080:80
        volumes:
            - "${PROJECT_ROOT}:/var/www/html:ro"
        networks:
            - app-network
        depends_on:
            - db
        restart: always
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
#         image: ivelin1936/m5_db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        restart: always
networks:
    app-network:
