version: "3.7"
services:
    web:
        image: "${DO_HUB_USR}/${WEB_IMG}"
        ports:
            - 80:80
        volumes:
            - "${PROJECT_ROOT}:/var/www/html:ro"
        networks:
            - m5-network
        depends_on:
            - db
        restart: always
    db:
        image: "${DO_HUB_USR}/${DB_IMG}"
        networks:
            - m5-network
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        restart: always
networks:
    m5-network:
